(()=>{
const KEY='latebook_calendar_v1';
const cal$=s=>document.querySelector(s), cal$$=s=>[...document.querySelectorAll(s)];
let events=JSON.parse(localStorage.getItem(KEY)||'[]');
let cursor=new Date(); cursor.setHours(12,0,0,0);
let selected=new Date(cursor);
let view='month';
let search='';
const pad2=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`;
const parseKey=k=>{const [y,m,d]=k.split('-').map(Number);return new Date(y,m-1,d,12)};
const weekdays=['일','월','화','수','목','금','토'];
const categoryLabel={work:'업무',important:'중요',personal:'개인',etc:'기타'};
function uid(){return crypto.randomUUID?crypto.randomUUID():`ev-${Date.now()}-${Math.random().toString(16).slice(2)}`}
function save(){localStorage.setItem(KEY,JSON.stringify(events))}
function occursOn(ev,d){const base=parseKey(ev.date), target=new Date(d);target.setHours(12,0,0,0);if(target<base)return false;if(ev.repeat==='daily')return true;if(ev.repeat==='weekly')return target.getDay()===base.getDay();if(ev.repeat==='monthly')return target.getDate()===base.getDate();return dateKey(target)===ev.date}
function filteredForDate(d){return events.filter(ev=>occursOn(ev,d)&&(!search||`${ev.title} ${ev.notes||''}`.toLowerCase().includes(search))).sort((a,b)=>(a.allDay===b.allDay?String(a.startTime||'').localeCompare(String(b.startTime||'')):a.allDay?-1:1))}
function eventTime(ev){return ev.allDay?'종일':`${ev.startTime||'--:--'}${ev.endTime?`–${ev.endTime}`:''}`}
function setTitle(){const t=cal$('#calendarTitle');if(!t)return;if(view==='month')t.textContent=`${cursor.getFullYear()}년 ${cursor.getMonth()+1}월`;else if(view==='week'){const s=startOfWeek(cursor),e=new Date(s);e.setDate(s.getDate()+6);t.textContent=`${s.getMonth()+1}월 ${s.getDate()}일 – ${e.getMonth()+1}월 ${e.getDate()}일`}else t.textContent=`${cursor.getFullYear()}년 ${cursor.getMonth()+1}월 ${cursor.getDate()}일`}
function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return x}
function chip(ev){return `<button class="cal-event-chip-v19 cat-${ev.category||'work'}" data-event-id="${ev.id}" type="button"><span>${ev.allDay?'':ev.startTime||''}</span>${escapeHtml(ev.title)}</button>`}
function escapeHtml(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function renderMonth(){const host=cal$('#calendarView');const y=cursor.getFullYear(),m=cursor.getMonth(),first=new Date(y,m,1,12),start=new Date(first);start.setDate(1-first.getDay());let html='<div class="month-view-v19"><div class="month-weekdays-v19">'+weekdays.map((w,i)=>`<span class="${i===0?'sun':''}${i===6?' sat':''}">${w}</span>`).join('')+'</div><div class="month-grid-v19">';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const evs=filteredForDate(d);const key=dateKey(d),other=d.getMonth()!==m,today=key===dateKey(new Date()),sel=key===dateKey(selected);html+=`<div class="month-day-v19 ${other?'other-month':''} ${today?'today':''} ${sel?'selected':''}" data-date="${key}" role="button" tabindex="0" aria-label="${key}"><span class="day-number-v19">${d.getDate()}</span><div class="day-events-v19">${evs.slice(0,3).map(chip).join('')}${evs.length>3?`<span class="more-events-v19">+${evs.length-3}개</span>`:''}</div></div>`}html+='</div></div>';host.innerHTML=html;bindCalendarItems()}
function renderWeek(){const host=cal$('#calendarView'),start=startOfWeek(cursor);let html='<div class="week-view-v19">';for(let i=0;i<7;i++){const d=new Date(start);d.setDate(start.getDate()+i);const evs=filteredForDate(d),key=dateKey(d),today=key===dateKey(new Date());html+=`<section class="week-day-v19 ${today?'today':''}" data-date="${key}"><header><span>${weekdays[d.getDay()]}</span><strong>${d.getDate()}</strong></header><div>${evs.length?evs.map(ev=>`<button class="week-event-v19 cat-${ev.category||'work'}" data-event-id="${ev.id}" type="button"><span>${eventTime(ev)}</span><b>${escapeHtml(ev.title)}</b></button>`).join(''):'<em>일정 없음</em>'}</div></section>`}html+='</div>';host.innerHTML=html;bindCalendarItems()}
function renderDay(){const host=cal$('#calendarView'),evs=filteredForDate(cursor);host.innerHTML=`<div class="day-view-v19"><div class="day-timeline-head-v19"><span>${weekdays[cursor.getDay()]}요일</span><strong>${cursor.getMonth()+1}월 ${cursor.getDate()}일</strong></div><div class="day-event-list-v19">${evs.length?evs.map(ev=>`<button class="day-event-card-v19 cat-${ev.category||'work'}" data-event-id="${ev.id}" type="button"><span>${eventTime(ev)}</span><div><strong>${escapeHtml(ev.title)}</strong><small>${escapeHtml(ev.notes||categoryLabel[ev.category]||'')}</small></div></button>`).join(''):'<div class="calendar-empty-v19">이 날짜에는 일정이 없습니다.<button type="button" id="emptyAddBtn">＋ 일정 추가</button></div>'}</div></div>`;bindCalendarItems();cal$('#emptyAddBtn')?.addEventListener('click',()=>openEditor(null,dateKey(cursor)))}
function renderAgenda(){const d=selected,evs=filteredForDate(d);cal$('#agendaWeekday').textContent=`${weekdays[d.getDay()]}요일`;cal$('#agendaDate').textContent=`${d.getMonth()+1}월 ${d.getDate()}일`;cal$('#agendaList').innerHTML=evs.length?evs.map(ev=>`<button class="agenda-event-v19 cat-${ev.category||'work'}" data-event-id="${ev.id}" type="button"><span>${eventTime(ev)}</span><strong>${escapeHtml(ev.title)}</strong><small>${categoryLabel[ev.category]||'일정'}${ev.repeat&&ev.repeat!=='none'?' · 반복':''}</small></button>`).join(''):'<div class="agenda-empty-v19">등록된 일정이 없습니다.</div>';cal$$('#agendaList [data-event-id]').forEach(b=>b.onclick=()=>openEditor(b.dataset.eventId))}
function render(){setTitle();if(view==='month')renderMonth();else if(view==='week')renderWeek();else renderDay();renderAgenda()}
function bindCalendarItems(){cal$$('[data-date]').forEach(el=>{const selectDate=e=>{if(e.target.closest?.('[data-event-id]'))return;selected=parseKey(el.dataset.date);if(view==='month')renderMonth();renderAgenda()};el.addEventListener('click',selectDate);el.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest?.('[data-event-id]')){e.preventDefault();selectDate(e)}})});cal$$('#calendarView [data-event-id]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openEditor(b.dataset.eventId)}))}
function openEditor(id,date){const dlg=cal$('#eventDialog'),ev=id?events.find(x=>x.id===id):null;cal$('#eventDialogTitle').textContent=ev?'일정 수정':'새 일정';cal$('#eventId').value=ev?.id||'';cal$('#eventTitleInput').value=ev?.title||'';cal$('#eventDateInput').value=ev?.date||date||dateKey(selected);cal$('#eventAllDayInput').checked=!!ev?.allDay;cal$('#eventStartInput').value=ev?.startTime||'09:00';cal$('#eventEndInput').value=ev?.endTime||'10:00';cal$('#eventCategoryInput').value=ev?.category||'work';cal$('#eventRepeatInput').value=ev?.repeat||'none';cal$('#eventNotesInput').value=ev?.notes||'';cal$('#eventDeleteBtn').style.visibility=ev?'visible':'hidden';toggleTimeRow();dlg.showModal()}
function toggleTimeRow(){cal$('#eventTimeRow').style.display=cal$('#eventAllDayInput').checked?'none':'grid'}
function closeEditor(){cal$('#eventDialog').close()}
function saveEvent(e){e.preventDefault();const id=cal$('#eventId').value||uid(),item={id,title:cal$('#eventTitleInput').value.trim(),date:cal$('#eventDateInput').value,allDay:cal$('#eventAllDayInput').checked,startTime:cal$('#eventAllDayInput').checked?'':cal$('#eventStartInput').value,endTime:cal$('#eventAllDayInput').checked?'':cal$('#eventEndInput').value,category:cal$('#eventCategoryInput').value,repeat:cal$('#eventRepeatInput').value,notes:cal$('#eventNotesInput').value.trim()};if(!item.title||!item.date)return;if(!item.allDay&&item.endTime&&item.startTime&&item.endTime<item.startTime){alert('종료시간은 시작시간보다 빠를 수 없습니다.');return}const idx=events.findIndex(x=>x.id===id);if(idx>=0)events[idx]=item;else events.push(item);save();selected=parseKey(item.date);cursor=new Date(selected);closeEditor();render()}
function deleteEvent(){const id=cal$('#eventId').value;if(!id)return;if(!confirm('이 일정을 삭제할까요?'))return;events=events.filter(x=>x.id!==id);save();closeEditor();render()}
function move(delta){if(view==='month')cursor.setMonth(cursor.getMonth()+delta);else if(view==='week')cursor.setDate(cursor.getDate()+delta*7);else cursor.setDate(cursor.getDate()+delta);selected=new Date(cursor);render()}
cal$('#calendarPrevBtn').onclick=()=>move(-1);cal$('#calendarNextBtn').onclick=()=>move(1);cal$('#calendarTodayBtn').onclick=()=>{cursor=new Date();cursor.setHours(12,0,0,0);selected=new Date(cursor);render()};cal$('#calendarAddBtn').onclick=()=>openEditor(null,dateKey(selected));cal$('#agendaAddBtn').onclick=()=>openEditor(null,dateKey(selected));cal$$('[data-cal-view]').forEach(b=>b.onclick=()=>{view=b.dataset.calView;cal$$('[data-cal-view]').forEach(x=>x.classList.toggle('active',x===b));render()});cal$('#calendarSearch').addEventListener('input',e=>{search=e.target.value.trim().toLowerCase();render()});cal$('#eventAllDayInput').onchange=toggleTimeRow;cal$('#eventCloseBtn').onclick=closeEditor;cal$('#eventCancelBtn').onclick=closeEditor;cal$('#eventDeleteBtn').onclick=deleteEvent;cal$('#eventForm').addEventListener('submit',saveEvent);
render();
})();